#if !defined(AFX_CODECINFO_H__D0B1C246_3D77_11D4_A6DD_009027D11084__INCLUDED_)
#define AFX_CODECINFO_H__D0B1C246_3D77_11D4_A6DD_009027D11084__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCodecCookie;

/////////////////////////////////////////////////////////////////////////////
// CCodecInfo wrapper class

class CCodecInfo : public COleDispatchDriver
{
public:
	CCodecInfo() {}		// Calls COleDispatchDriver default constructor
	CCodecInfo(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCodecInfo(const CCodecInfo& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CCodecCookie GetCodecCookie();
	CString GetCodecName();
	long GetOldestCompatiblePlayer();
	CCodecCookie GetCodecForVersion(long PlayerVersion);
	CString GetCodecDescription();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CODECINFO_H__D0B1C246_3D77_11D4_A6DD_009027D11084__INCLUDED_)
