// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rmfile.h"


/////////////////////////////////////////////////////////////////////////////
// CRmFile properties

/////////////////////////////////////////////////////////////////////////////
// CRmFile operations

CString CRmFile::GetTitle()
{
	CString result;
	InvokeHelper(0x1131, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CRmFile::SetTitle(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1131, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CRmFile::GetAuthor()
{
	CString result;
	InvokeHelper(0x1132, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CRmFile::SetAuthor(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1132, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CRmFile::GetCopyright()
{
	CString result;
	InvokeHelper(0x1133, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CRmFile::SetCopyright(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1133, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CRmFile::GetDescription()
{
	CString result;
	InvokeHelper(0x1134, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CRmFile::SetDescription(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1134, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString CRmFile::GetKeywords()
{
	CString result;
	InvokeHelper(0x1135, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CRmFile::SetKeywords(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1135, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

long CRmFile::GetRating()
{
	long result;
	InvokeHelper(0x1136, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CRmFile::SetRating(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1136, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

BOOL CRmFile::GetIndexable()
{
	BOOL result;
	InvokeHelper(0x1137, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CRmFile::SetIndexable(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x1137, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CRmFile::GetSelectiveRecord()
{
	BOOL result;
	InvokeHelper(0x1138, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CRmFile::SetSelectiveRecord(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x1138, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CRmFile::GetMobilePlay()
{
	BOOL result;
	InvokeHelper(0x1139, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CRmFile::SetMobilePlay(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x1139, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

long CRmFile::GetStartTime()
{
	long result;
	InvokeHelper(0x113a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CRmFile::SetStartTime(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x113a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CRmFile::GetEndTime()
{
	long result;
	InvokeHelper(0x113b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CRmFile::SetEndTime(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x113b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

BOOL CRmFile::GetIsSingleRate()
{
	BOOL result;
	InvokeHelper(0x1141, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CRmFile::GetIsSureStream()
{
	BOOL result;
	InvokeHelper(0x1142, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CRmFile::GetHasAudio()
{
	BOOL result;
	InvokeHelper(0x1143, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CRmFile::GetHasVideo()
{
	BOOL result;
	InvokeHelper(0x1144, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CRmFile::GetHasEvents()
{
	BOOL result;
	InvokeHelper(0x1145, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CRmFile::GetHasImageMaps()
{
	BOOL result;
	InvokeHelper(0x1146, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CRmFile::GetVideoHeight()
{
	long result;
	InvokeHelper(0x1147, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long CRmFile::GetVideoWidth()
{
	long result;
	InvokeHelper(0x1148, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CRmFile::GetStringProperty(LPCTSTR PropertyName, BSTR* Value)
{
	static BYTE parms[] =
		VTS_BSTR VTS_PBSTR;
	InvokeHelper(0x113c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PropertyName, Value);
}

void CRmFile::SetStringProperty(LPCTSTR PropertyName, LPCTSTR Value)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x113d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PropertyName, Value);
}

void CRmFile::GetNumberProperty(LPCTSTR PropertyName, long* Value)
{
	static BYTE parms[] =
		VTS_BSTR VTS_PI4;
	InvokeHelper(0x113e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PropertyName, Value);
}

void CRmFile::SetNumberProperty(LPCTSTR PropertyName, long Value)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x113f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PropertyName, Value);
}

void CRmFile::RemoveProperty(LPCTSTR PropertyName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1140, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PropertyName);
}

void CRmFile::Open(LPCTSTR FilePathname)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1149, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FilePathname);
}

void CRmFile::Save(LPCTSTR FilePathname)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x114a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FilePathname);
}

void CRmFile::AppendRmFile(LPCTSTR FilePathname)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x114b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FilePathname);
}

void CRmFile::AddImageMaps(LPCTSTR FilePathname)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x114c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FilePathname);
}

void CRmFile::AddEvents(LPCTSTR FilePathname)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x114d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 FilePathname);
}

CString CRmFile::GetErrorString(long lErrorCode)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x114e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		lErrorCode);
	return result;
}
