// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "codecinfo.h"

// Dispatch interfaces referenced by this interface
#include "codeccookie.h"


/////////////////////////////////////////////////////////////////////////////
// CCodecInfo properties

/////////////////////////////////////////////////////////////////////////////
// CCodecInfo operations

CCodecCookie CCodecInfo::GetCodecCookie()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xddf, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CCodecCookie(pDispatch);
}

CString CCodecInfo::GetCodecName()
{
	CString result;
	InvokeHelper(0xde0, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CCodecInfo::GetOldestCompatiblePlayer()
{
	long result;
	InvokeHelper(0xde1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CCodecCookie CCodecInfo::GetCodecForVersion(long PlayerVersion)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xde2, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		PlayerVersion);
	return CCodecCookie(pDispatch);
}

CString CCodecInfo::GetCodecDescription()
{
	CString result;
	InvokeHelper(0xde3, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}
