#if !defined(AFX_ENUMIDISPATCH_H__D0B1C243_3D77_11D4_A6DD_009027D11084__INCLUDED_)
#define AFX_ENUMIDISPATCH_H__D0B1C243_3D77_11D4_A6DD_009027D11084__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEnumIDispatch wrapper class

class CEnumIDispatch : public COleDispatchDriver
{
public:
	CEnumIDispatch() {}		// Calls COleDispatchDriver default constructor
	CEnumIDispatch(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CEnumIDispatch(const CEnumIDispatch& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	LPDISPATCH First();
	LPDISPATCH Next();
	long GetCount();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ENUMIDISPATCH_H__D0B1C243_3D77_11D4_A6DD_009027D11084__INCLUDED_)
