// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "enumidispatch.h"


/////////////////////////////////////////////////////////////////////////////
// CEnumIDispatch properties

/////////////////////////////////////////////////////////////////////////////
// CEnumIDispatch operations

LPDISPATCH CEnumIDispatch::First()
{
	LPDISPATCH result;
	InvokeHelper(0xfd3, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

LPDISPATCH CEnumIDispatch::Next()
{
	LPDISPATCH result;
	InvokeHelper(0xfd4, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

long CEnumIDispatch::GetCount()
{
	long result;
	InvokeHelper(0xfd5, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
