#if !defined(AFX_RMFILE_H__D0B1C242_3D77_11D4_A6DD_009027D11084__INCLUDED_)
#define AFX_RMFILE_H__D0B1C242_3D77_11D4_A6DD_009027D11084__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRmFile wrapper class

class CRmFile : public COleDispatchDriver
{
public:
	CRmFile() {}		// Calls COleDispatchDriver default constructor
	CRmFile(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRmFile(const CRmFile& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetTitle();
	void SetTitle(LPCTSTR lpszNewValue);
	CString GetAuthor();
	void SetAuthor(LPCTSTR lpszNewValue);
	CString GetCopyright();
	void SetCopyright(LPCTSTR lpszNewValue);
	CString GetDescription();
	void SetDescription(LPCTSTR lpszNewValue);
	CString GetKeywords();
	void SetKeywords(LPCTSTR lpszNewValue);
	long GetRating();
	void SetRating(long nNewValue);
	BOOL GetIndexable();
	void SetIndexable(BOOL bNewValue);
	BOOL GetSelectiveRecord();
	void SetSelectiveRecord(BOOL bNewValue);
	BOOL GetMobilePlay();
	void SetMobilePlay(BOOL bNewValue);
	long GetStartTime();
	void SetStartTime(long nNewValue);
	long GetEndTime();
	void SetEndTime(long nNewValue);
	BOOL GetIsSingleRate();
	BOOL GetIsSureStream();
	BOOL GetHasAudio();
	BOOL GetHasVideo();
	BOOL GetHasEvents();
	BOOL GetHasImageMaps();
	long GetVideoHeight();
	long GetVideoWidth();
	void GetStringProperty(LPCTSTR PropertyName, BSTR* Value);
	void SetStringProperty(LPCTSTR PropertyName, LPCTSTR Value);
	void GetNumberProperty(LPCTSTR PropertyName, long* Value);
	void SetNumberProperty(LPCTSTR PropertyName, long Value);
	void RemoveProperty(LPCTSTR PropertyName);
	void Open(LPCTSTR FilePathname);
	void Save(LPCTSTR FilePathname);
	void AppendRmFile(LPCTSTR FilePathname);
	void AddImageMaps(LPCTSTR FilePathname);
	void AddEvents(LPCTSTR FilePathname);
	CString GetErrorString(long lErrorCode);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMFILE_H__D0B1C242_3D77_11D4_A6DD_009027D11084__INCLUDED_)
