#if !defined(AFX_TARGETAUDIENCEINFO_H__D0B1C245_3D77_11D4_A6DD_009027D11084__INCLUDED_)
#define AFX_TARGETAUDIENCEINFO_H__D0B1C245_3D77_11D4_A6DD_009027D11084__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCodecCookie;

/////////////////////////////////////////////////////////////////////////////
// CTargetAudienceInfo wrapper class

class CTargetAudienceInfo : public COleDispatchDriver
{
public:
	CTargetAudienceInfo() {}		// Calls COleDispatchDriver default constructor
	CTargetAudienceInfo(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTargetAudienceInfo(const CTargetAudienceInfo& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetTargetAudienceId();
	CString GetTargetAudienceName();
	float GetTargetBitrate();
	void SetTargetBitrate(float newValue);
	float GetMaxFrameRate();
	void SetMaxFrameRate(float newValue);
	CCodecCookie GetVideoCodec();
	void SetVideoCodec(LPDISPATCH newValue);
	CCodecCookie GetAudioCodec(long TargetAudienceType, long AudioContent);
	void SetAudioCodec(long TargetAudienceType, long AudioContent, LPDISPATCH newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TARGETAUDIENCEINFO_H__D0B1C245_3D77_11D4_A6DD_009027D11084__INCLUDED_)
